version: "3.2"
services:
  web:
    build: ./docker
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/docroot/
    volumes:
      - ./:/var/www/html/
      - ./docker/apache/vhost.conf:/usr/local/apache2/conf/httpd.conf
    links:
      - db

  db:
    image: mysql:5.7.25
    restart: always
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/database.sql:/docker-entrypoint-initdb.d/database.sql  
